version: "3.9"
    
services:
  db:
    image: mariaDB:10

    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootdb
      MYSQL_DATABASE: projarka
      MYSQL_USER: user
      MYSQL_PASSWORD: user
