version: "3.9"
    
services:
  db:
    image: mariaDB:10.1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootdb
      MYSQL_DATABASE: projarka
      MYSQL_USER: user
      MYSQL_PASSWORD: user
 
  back:
    image: python:3
    restart: always
    environment:
      WORKDIR: /usr/src/app
    volumes:
      - back/requirements.txt:./
      - back/*:./
    command: bash -c > "
        pip3 install --no-cache-dir -r requirements.txt
        && python3 ./api.py"
    
    
 front:
    image: nginx
    restart: always
    volumes:
      - front/index.html:/usr/share/nginx/html
    ports:
      - "8080:80"
 
 
